export const ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
export const USER_SCREENS = 'USER_SCREENS';

export const HOME_SCREEN = 'HOME_SCREEN';
export const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';
export const CART_SCREEN = 'CART_SCREEN';
export const CHAT_SCREEN = 'CHAT_SCREEN';
export const COMPLAINTS_SCREEN = 'COMPLAINTS_SCREEN';
export const SUBSCRIPTION_SCREEN = 'SUBSCRIPTION_SCREEN';

export const HOME_TAB = 'HOME_TAB';
export const SUPPORT_TAB = 'SUPPORT_TAB';
export const PROFILE_TAB = 'PROFILE_TAB';
